// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContentService.proto

package com.gaian.grpc;

public final class ContentService {
  private ContentService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gaian_grpc_GetMetaDataRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gaian_grpc_GetMetaDataRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_gaian_grpc_GetMetaDataResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_gaian_grpc_GetMetaDataResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\024ContentService.proto\022\016com.gaian.grpc\"&" +
      "\n\022GetMetaDataRequest\022\020\n\010filePath\030\001 \001(\t\"$" +
      "\n\023GetMetaDataResponse\022\r\n\005files\030\001 \003(\t2l\n\022" +
      "GetMetaDataService\022V\n\013getMetaData\022\".com." +
      "gaian.grpc.GetMetaDataRequest\032#.com.gaia" +
      "n.grpc.GetMetaDataResponseB\002P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_gaian_grpc_GetMetaDataRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_gaian_grpc_GetMetaDataRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gaian_grpc_GetMetaDataRequest_descriptor,
        new String[] { "FilePath", });
    internal_static_com_gaian_grpc_GetMetaDataResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_gaian_grpc_GetMetaDataResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_gaian_grpc_GetMetaDataResponse_descriptor,
        new String[] { "Files", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
