// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChunkService.proto

package com.gaian.grpc;

public interface GetChunkRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gaian.grpc.GetChunkRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string filePath = 1;</code>
   */
  String getFilePath();
  /**
   * <code>string filePath = 1;</code>
   */
  com.google.protobuf.ByteString
      getFilePathBytes();
}
