// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ChunkService.proto

package com.gaian.grpc;

public interface GetChunkResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gaian.grpc.GetChunkResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bytes data = 1;</code>
   */
  com.google.protobuf.ByteString getData();
}
