// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ContentService.proto

package com.gaian.grpc;

public interface GetMetaDataResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.gaian.grpc.GetMetaDataResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string files = 1;</code>
   */
  java.util.List<String>
      getFilesList();
  /**
   * <code>repeated string files = 1;</code>
   */
  int getFilesCount();
  /**
   * <code>repeated string files = 1;</code>
   */
  String getFiles(int index);
  /**
   * <code>repeated string files = 1;</code>
   */
  com.google.protobuf.ByteString
      getFilesBytes(int index);
}
